export const mainCategoryMap: { [key: string]: string } = {
  health: 'accommodation',
  rent: 'accommodation',
  internet: 'accommodation',
  utilities: 'accommodation',
  shoes: 'clothes',
  accessories: 'clothes',
  clothes: 'clothes',
  foods: 'foods',
  restaurant: 'foods',
  snack: 'foods',
  drink: 'foods',
  hobby: 'hobby',
  education: 'hobby',
  transport: 'transport',
  car_insurance: 'transport',
  train_ticket: 'transport',
  gasoline: 'transport',
  travel: 'transport',
};
